apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: koduck-prod

resources:
  - ./namespace.yaml
  - ../../base/frontend.yaml
  - ../../base/koduck-auth.yaml
  - ../../base/koduck-user.yaml
  - ../../base/koduck-knowledge.yaml
  - ../../base/koduck-ai.yaml
  - ../../base/koduck-memory.yaml
  - ../../base/minio.yaml
  - ../../base/postgres.yaml
  - ./apisix.yaml
  - ./minio.yaml

patchesStrategicMerge:
  - ./frontend.yaml
  - ./koduck-auth-secrets.yaml
  - ./koduck-user-secrets.yaml
  - ./koduck-knowledge.yaml
  - ./koduck-memory.yaml

namePrefix: prod-

labels:
  - pairs:
      environment: prod
    includeSelectors: true
