apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: koduck-prod

resources:
  - ./namespace.yaml
  - ../../base/frontend.yaml
  - ./apisix.yaml

patchesStrategicMerge:
  - ./frontend.yaml

namePrefix: prod-

labels:
  - pairs:
      environment: prod
    includeSelectors: true
