package com.koduck.controller;

import io.swagger.v3.oas.annotations.tags.Tag;

import com.koduck.dto.ApiResponse;
import com.koduck.dto.ai.BacktestInterpretRequest;
import com.koduck.dto.ai.BacktestInterpretResponse;
import com.koduck.dto.ai.ChatStreamRequest;
import com.koduck.dto.ai.RiskAssessmentRequest;
import com.koduck.dto.ai.RiskAssessmentResponse;
import com.koduck.dto.ai.StockAnalysisRequest;
import com.koduck.dto.ai.StockAnalysisResponse;
import com.koduck.dto.ai.StrategyRecommendRequest;
import com.koduck.dto.ai.StrategyRecommendResponse;
import com.koduck.security.UserPrincipal;
import com.koduck.service.AiAnalysisService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.Objects;

/**
 * REST API controller exposing AI analysis endpoints.
 *
 * <p>Clients use this controller to request stock analysis, strategy
 * recommendations, backtest interpretation, and portfolio risk assessment.
 * All endpoints require authenticated credentials.</p>
 *
 * @author GitHub Copilot
 * @date 2026-03-05
 */
@RestController
@RequestMapping("/api/v1/ai")
@RequiredArgsConstructor
@Tag(name = "AI分析", description = "智能股票分析、策略推荐、风险评估等AI分析接口")
@Slf4j
public class AiAnalysisController {

    private final AiAnalysisService aiAnalysisService;

    /**
     * Perform an AI-driven stock analysis.
     *
     * <p>The results are generated by the {@link AiAnalysisService} and include
     * technical, fundamental and sentiment assessments.</p>
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        request payload containing symbol, market and analysis
     *                       type
     * @return a successful {@link ApiResponse} wrapping the analysis result
     */
    @PostMapping("/analyze")
    public ApiResponse<StockAnalysisResponse> analyzeStock(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody StockAnalysisRequest request) {

        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/analyze: user={}, symbol={}, question={}", userId, request.getSymbol(), request.getQuestion());

        StockAnalysisResponse response = aiAnalysisService.analyzeStock(userId, request);
        return ApiResponse.success(response);
    }

    /**
     * Proxy chat stream request through backend for unified AI access.
     */
    @PostMapping(value = "/chat/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public SseEmitter chatStream(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody ChatStreamRequest request) {

        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/chat/stream: user={}, provider={}", userId, request.getProvider());
        return aiAnalysisService.streamChat(userId, request);
    }

    /**
     * Generate strategy recommendations for the user.
     *
     * <p>The request includes risk preference and investment horizon. The
     * service will return a list of candidate strategies along with a
     * suggested asset allocation.</p>
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        strategy recommendation request data
     * @return an {@link ApiResponse} with strategy recommendations
     */
    @PostMapping("/strategy-recommend")
    public ApiResponse<StrategyRecommendResponse> recommendStrategies(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody StrategyRecommendRequest request) {

        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/strategy-recommend: user={}, risk={}",
                 userId, request.getRiskPreference());

        StrategyRecommendResponse response = aiAnalysisService.recommendStrategies(userId, request);
        return ApiResponse.success(response);
    }

    /**
     * Interpret a previously run backtest result.
     *
     * <p>The user must own the backtest result identified in the request.</p>
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        contains the identifier of the backtest result
     * @return an {@link ApiResponse} containing interpretation details
     */
    @PostMapping("/interpret-backtest")
    public ApiResponse<BacktestInterpretResponse> interpretBacktest(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody BacktestInterpretRequest request) {

        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/interpret-backtest: user={}, backtestId={}",
                 userId, request.getBacktestResultId());

        BacktestInterpretResponse response = aiAnalysisService.interpretBacktest(
            userId,
            request.getBacktestResultId()
        );
        return ApiResponse.success(response);
    }

    /**
     * Perform a risk assessment on the user's portfolio.
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        contains the portfolio identifier to evaluate
     * @return an {@link ApiResponse} with risk metrics and suggestions
     */
    @PostMapping("/risk-assessment")
    public ApiResponse<RiskAssessmentResponse> assessRisk(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody RiskAssessmentRequest request) {

        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/risk-assessment: user={}, portfolioId={}",
                 userId, request.getPortfolioId());

        RiskAssessmentResponse response = aiAnalysisService.assessRisk(
            userId,
            request.getPortfolioId()
        );
        return ApiResponse.success(response);
    }

    private Long requireUserId(UserPrincipal userPrincipal) {
        UserPrincipal principal = Objects.requireNonNull(userPrincipal, "authenticated user is required");
        return principal.getUser().getId();
    }
}
