package com.koduck.controller;

import com.koduck.controller.support.AuthenticatedUserResolver;
import com.koduck.dto.ApiResponse;
import com.koduck.dto.backtest.BacktestResultDto;
import com.koduck.dto.backtest.BacktestTradeDto;
import com.koduck.dto.backtest.RunBacktestRequest;
import com.koduck.security.UserPrincipal;
import com.koduck.service.BacktestService;
import jakarta.validation.Valid;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST API controller for backtest operations.
 *
 * <p>All endpoints are secured and operate on the currently authenticated user.
 * Business logic is delegated to {@link com.koduck.service.BacktestService}.
 *
 * @author GitHub Copilot
 * @date 2026-03-31
 */
@RestController
@RequestMapping("/api/v1/backtest")
@Validated
@Slf4j
@RequiredArgsConstructor
public class BacktestController {

    private final AuthenticatedUserResolver authenticatedUserResolver;
    private final BacktestService backtestService;

    /**
     * Retrieve all backtest results belonging to the authenticated user.
     *
     * @param userPrincipal the currently authenticated principal, injected by
     *                      Spring Security
     * @return a successful {@link com.koduck.dto.ApiResponse} containing a list of
     *         {@link com.koduck.dto.backtest.BacktestResultDto}
     */
    @GetMapping
    public ApiResponse<List<BacktestResultDto>> getBacktestResults(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        Long userId = requireUserId(userPrincipal);
        log.debug("GET /api/v1/backtest: user={}", userId);
        List<BacktestResultDto> results = backtestService.getBacktestResults(userId);
        return ApiResponse.success(results);
    }
    /**
     * Retrieve a single backtest result by its identifier.
     *
     * @param userPrincipal the authenticated principal
     * @param id            the unique identifier of the backtest result
     * @return the corresponding {@link com.koduck.dto.backtest.BacktestResultDto}
     */
    @GetMapping("/{id}")
    public ApiResponse<BacktestResultDto> getBacktestResult(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable Long id) {
        Long userId = requireUserId(userPrincipal);
        log.debug("GET /api/v1/backtest/{}: user={}", id, userId);
        BacktestResultDto result = backtestService.getBacktestResult(userId, id);
        return ApiResponse.success(result);
    }
    /**
     * Execute a new backtest using the supplied request parameters.
     *
     * @param userPrincipal the authenticated principal
     * @param request       validated backtest configuration
     * @return the {@link com.koduck.dto.backtest.BacktestResultDto} generated by
     *         the service
     */
    @PostMapping("/run")
    public ApiResponse<BacktestResultDto> runBacktest(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody RunBacktestRequest request) {
        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/backtest/run: user={}, strategyId={}, symbol={}",
                 userId, request.strategyId(), request.symbol());
        BacktestResultDto result = backtestService.runBacktest(userId, request);
        return ApiResponse.success(result);
    }

    /**
     * List all trades produced by a given backtest result.
     *
     * @param userPrincipal the authenticated principal
     * @param id            the backtest result identifier
     * @return list of {@link com.koduck.dto.backtest.BacktestTradeDto}
     */
    @GetMapping("/{id}/trades")
    public ApiResponse<List<BacktestTradeDto>> getBacktestTrades(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable Long id) {
        Long userId = requireUserId(userPrincipal);
        log.debug("GET /api/v1/backtest/{}/trades: user={}", id, userId);
        List<BacktestTradeDto> trades = backtestService.getBacktestTrades(userId, id);
        return ApiResponse.success(trades);
    }
    /**
     * Remove a backtest result owned by the current user.
     *
     * @param userPrincipal the authenticated principal
     * @param id            identifier of the backtest result to delete
     * @return a successful empty {@link com.koduck.dto.ApiResponse}
     */
    @DeleteMapping("/{id}")
    public ApiResponse<Void> deleteBacktestResult(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable Long id) {
        Long userId = requireUserId(userPrincipal);
        log.debug("DELETE /api/v1/backtest/{}: user={}", id, userId);
        backtestService.deleteBacktestResult(userId, id);
        return ApiResponse.successNoContent();
    }

    private Long requireUserId(UserPrincipal userPrincipal) {
        return authenticatedUserResolver.requireUserId(userPrincipal);
    }
}
