package com.koduck.controller;

import com.koduck.dto.ApiResponse;
import com.koduck.dto.backtest.*;
import com.koduck.security.UserPrincipal;
import com.koduck.service.BacktestService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST API controller for backtest operations.
 *
 * <p>All endpoints are secured and operate on the currently authenticated user.
 * Business logic is delegated to {@link com.koduck.service.BacktestService}.
 */
@RestController
@RequestMapping("/api/v1/backtest")
@RequiredArgsConstructor
@Validated
@Slf4j
public class BacktestController {
    
    private final BacktestService backtestService;
    
    /**
     * Retrieve all backtest results belonging to the authenticated user.
     *
     * @param userPrincipal the currently authenticated principal, injected by
     *                      Spring Security
     * @return a successful {@link com.koduck.dto.ApiResponse} containing a list of
     *         {@link com.koduck.dto.backtest.BacktestResultDto}
     */
    @GetMapping
    public ApiResponse<List<BacktestResultDto>> getBacktestResults(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        
        log.debug("GET /api/v1/backtest: user={}", userPrincipal.getUser().getId());
        
        List<BacktestResultDto> results = backtestService.getBacktestResults(userPrincipal.getUser().getId());
        return ApiResponse.success(results);
    }
    
    /**
     * Retrieve a single backtest result by its identifier.
     *
     * @param userPrincipal the authenticated principal
     * @param id            the unique identifier of the backtest result
     * @return the corresponding {@link com.koduck.dto.backtest.BacktestResultDto}
     */
    @GetMapping("/{id}")
    public ApiResponse<BacktestResultDto> getBacktestResult(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable Long id) {
        
        log.debug("GET /api/v1/backtest/{}: user={}", id, userPrincipal.getUser().getId());
        
        BacktestResultDto result = backtestService.getBacktestResult(userPrincipal.getUser().getId(), id);
        return ApiResponse.success(result);
    }
    
    /**
     * Execute a new backtest using the supplied request parameters.
     *
     * @param userPrincipal the authenticated principal
     * @param request       validated backtest configuration
     * @return the {@link com.koduck.dto.backtest.BacktestResultDto} generated by
     *         the service
     */
    @PostMapping("/run")
    public ApiResponse<BacktestResultDto> runBacktest(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody RunBacktestRequest request) {
        
        log.debug("POST /api/v1/backtest/run: user={}, strategyId={}, symbol={}", 
                 userPrincipal.getUser().getId(), request.strategyId(), request.symbol());
        
        BacktestResultDto result = backtestService.runBacktest(userPrincipal.getUser().getId(), request);
        return ApiResponse.success(result);
    }
    
    /**
     * List all trades produced by a given backtest result.
     *
     * @param userPrincipal the authenticated principal
     * @param id            the backtest result identifier
     * @return list of {@link com.koduck.dto.backtest.BacktestTradeDto}
     */
    @GetMapping("/{id}/trades")
    public ApiResponse<List<BacktestTradeDto>> getBacktestTrades(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable Long id) {
        
        log.debug("GET /api/v1/backtest/{}/trades: user={}", id, userPrincipal.getUser().getId());
        
        List<BacktestTradeDto> trades = backtestService.getBacktestTrades(userPrincipal.getUser().getId(), id);
        return ApiResponse.success(trades);
    }
    
    /**
     * Remove a backtest result owned by the current user.
     *
     * @param userPrincipal the authenticated principal
     * @param id            identifier of the backtest result to delete
     * @return a successful empty {@link com.koduck.dto.ApiResponse}
     */
    @DeleteMapping("/{id}")
    public ApiResponse<Void> deleteBacktestResult(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable Long id) {
        
        log.debug("DELETE /api/v1/backtest/{}: user={}", id, userPrincipal.getUser().getId());
        
        backtestService.deleteBacktestResult(userPrincipal.getUser().getId(), id);
        return ApiResponse.success();
    }
}
