CREATE TABLE IF NOT EXISTS memory_units (
    memory_unit_id UUID PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    session_id UUID NOT NULL,
    entry_range_start BIGINT NOT NULL,
    entry_range_end BIGINT NOT NULL,
    memory_kind VARCHAR(64) NULL,
    domain_class_primary VARCHAR(64) NULL,
    summary TEXT NULL,
    snippet TEXT NULL,
    source_uri VARCHAR(1024) NOT NULL,
    summary_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    salience_score NUMERIC(5, 4) NULL,
    time_bucket VARCHAR(32) NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_memory_units_entry_range
        CHECK (entry_range_end >= entry_range_start),
    CONSTRAINT chk_memory_units_memory_kind
        CHECK (memory_kind IS NULL OR memory_kind IN ('summary', 'fact')),
    CONSTRAINT chk_memory_units_summary_status
        CHECK (summary_status IN ('pending', 'ready', 'failed')),
    CONSTRAINT chk_memory_units_summary_ready_requires_summary
        CHECK (
            summary_status <> 'ready'
            OR (summary IS NOT NULL AND BTRIM(summary) <> '')
        ),
    CONSTRAINT chk_memory_units_salience_score
        CHECK (
            salience_score IS NULL
            OR (salience_score >= 0 AND salience_score <= 1)
        )
);

CREATE INDEX IF NOT EXISTS idx_memory_units_tenant_session_created_at
    ON memory_units (tenant_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_units_tenant_kind_created_at
    ON memory_units (tenant_id, memory_kind, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_units_tenant_domain_created_at
    ON memory_units (tenant_id, domain_class_primary, created_at DESC);

COMMENT ON TABLE memory_units IS
    'Anchored memory retrieval baseline table. Each row materializes one memory unit over one or more contiguous memory entries.';

COMMENT ON COLUMN memory_units.memory_unit_id IS
    'Stable identifier for one retrievable memory unit.';
COMMENT ON COLUMN memory_units.tenant_id IS
    'Tenant boundary for all retrieval and write paths.';
COMMENT ON COLUMN memory_units.session_id IS
    'Session lineage retained for scoped retrieval and traceability.';
COMMENT ON COLUMN memory_units.entry_range_start IS
    'Inclusive starting memory_entries.sequence_num covered by this unit.';
COMMENT ON COLUMN memory_units.entry_range_end IS
    'Inclusive ending memory_entries.sequence_num covered by this unit.';
COMMENT ON COLUMN memory_units.memory_kind IS
    'V1: NULL means generic conversation unit. Non-NULL materialized kinds are limited to summary and fact.';
COMMENT ON COLUMN memory_units.domain_class_primary IS
    'Projection field derived from domain anchors, not an independent source of truth.';
COMMENT ON COLUMN memory_units.summary IS
    'Materialized summary text. Required only when summary_status is ready.';
COMMENT ON COLUMN memory_units.snippet IS
    'Stable retrieval display text generated by write path or derived from L0/summary.';
COMMENT ON COLUMN memory_units.source_uri IS
    'Primary trace-back URI. Full replay for multi-entry units depends on entry_range_start and entry_range_end.';
COMMENT ON COLUMN memory_units.summary_status IS
    'Closed set: pending, ready, failed. Only ready rows may require a non-empty summary.';
COMMENT ON COLUMN memory_units.salience_score IS
    'Optional salience hint used for ranking; expected range is 0..1.';
COMMENT ON COLUMN memory_units.time_bucket IS
    'Optional coarse-grained temporal bucket used only as a sorting signal.';
