-- Rebuild kline_data as a partitioned table.
-- NOTE: This migration intentionally drops the old table and all existing kline rows.

DROP TABLE IF EXISTS kline_data CASCADE;

CREATE TABLE kline_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    market VARCHAR(20) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    kline_time TIMESTAMP NOT NULL,
    open_price DECIMAL(18, 8) NOT NULL,
    high_price DECIMAL(18, 8) NOT NULL,
    low_price DECIMAL(18, 8) NOT NULL,
    close_price DECIMAL(18, 8) NOT NULL,
    volume BIGINT,
    amount DECIMAL(24, 8),
    pre_close_price DECIMAL(18, 8),
    is_suspended BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kline_data_pkey PRIMARY KEY (id, timeframe, kline_time),
    CONSTRAINT uk_kline_data UNIQUE (market, symbol, timeframe, kline_time)
) PARTITION BY LIST (timeframe);

COMMENT ON TABLE kline_data IS 'Historical K-line data, partitioned by timeframe and kline_time';

-- Level-1 partitions by timeframe, each sub-partitioned by time range.
CREATE TABLE kline_data_tf_1m PARTITION OF kline_data
    FOR VALUES IN ('1m') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_5m PARTITION OF kline_data
    FOR VALUES IN ('5m') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_15m PARTITION OF kline_data
    FOR VALUES IN ('15m') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_30m PARTITION OF kline_data
    FOR VALUES IN ('30m') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_60m PARTITION OF kline_data
    FOR VALUES IN ('60m') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_1d PARTITION OF kline_data
    FOR VALUES IN ('1D') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_1w PARTITION OF kline_data
    FOR VALUES IN ('1W') PARTITION BY RANGE (kline_time);
CREATE TABLE kline_data_tf_1mon PARTITION OF kline_data
    FOR VALUES IN ('1M') PARTITION BY RANGE (kline_time);

-- Fallback for unexpected timeframes to prevent ingestion failures.
CREATE TABLE kline_data_tf_default PARTITION OF kline_data DEFAULT;

-- Minute partitions: monthly partitions from 2020-01 to 2030-12.
DO $$
DECLARE
    tf TEXT;
    start_ts DATE;
    end_ts DATE;
    parent_name TEXT;
    leaf_name TEXT;
BEGIN
    FOR tf IN SELECT unnest(ARRAY['1m', '5m', '15m', '30m', '60m']) LOOP
        parent_name := format('kline_data_tf_%s', lower(tf));
        start_ts := DATE '2020-01-01';
        WHILE start_ts < DATE '2031-01-01' LOOP
            end_ts := (start_ts + INTERVAL '1 month')::DATE;
            leaf_name := format('kline_data_%s_%s', lower(tf), to_char(start_ts, 'YYYY_MM'));
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                leaf_name,
                parent_name,
                start_ts,
                end_ts
            );
            start_ts := end_ts;
        END LOOP;
    END LOOP;
END $$;

-- Daily/Weekly/Monthly partitions: yearly partitions from 1990 to 2030.
DO $$
DECLARE
    tf TEXT;
    tf_name TEXT;
    start_ts DATE;
    end_ts DATE;
    parent_name TEXT;
    leaf_name TEXT;
BEGIN
    FOR tf, tf_name IN
        SELECT * FROM (VALUES
            ('1D', '1d'),
            ('1W', '1w'),
            ('1M', '1mon')
        ) AS t(tf, tf_name)
    LOOP
        parent_name := format('kline_data_tf_%s', tf_name);
        start_ts := DATE '1990-01-01';
        WHILE start_ts < DATE '2031-01-01' LOOP
            end_ts := (start_ts + INTERVAL '1 year')::DATE;
            leaf_name := format('kline_data_%s_%s', tf_name, to_char(start_ts, 'YYYY'));
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                leaf_name,
                parent_name,
                start_ts,
                end_ts
            );
            start_ts := end_ts;
        END LOOP;
    END LOOP;
END $$;

-- Parent-level indexes for common query patterns.
CREATE INDEX IF NOT EXISTS idx_kline_market_symbol ON kline_data(market, symbol);
CREATE INDEX IF NOT EXISTS idx_kline_timeframe ON kline_data(timeframe);
CREATE INDEX IF NOT EXISTS idx_kline_time ON kline_data(kline_time);
CREATE INDEX IF NOT EXISTS idx_kline_composite ON kline_data(market, symbol, timeframe, kline_time DESC);
