//! Generated protobuf code for all gRPC service contracts.
//!
//! `tonic::include_proto!` places generated types directly at this module level.
//! The `build.rs` uses `extern_path` for `koduck.contract.v1` so that service protos
//! reference contract types via `crate::clients::proto::RequestMeta` etc.

// Contract types (RequestMeta, ErrorDetail, Capability) - generated by pass 1
tonic::include_proto!("koduck.contract.v1");

// Service types - generated by pass 2 (extern_path resolves contract references)
tonic::include_proto!("koduck.memory.v1");
tonic::include_proto!("koduck.tool.v1");
tonic::include_proto!("koduck.llm.v1");

// Re-export key client/server traits for convenient orchestrator injection
pub use memory_service_client::MemoryServiceClient;
pub use memory_service_server::{MemoryService, MemoryServiceServer};
pub use tool_service_client::ToolServiceClient;
pub use tool_service_server::{ToolService, ToolServiceServer};
pub use llm_service_client::LlmServiceClient;
pub use llm_service_server::{LlmService, LlmServiceServer};

/// File descriptor set for gRPC server reflection.
pub const FILE_DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("koduck_ai");
