package com.koduck.controller.ai;

import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.http.MediaType;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import com.koduck.controller.support.AuthenticatedUserResolver;
import com.koduck.dto.ApiResponse;
import com.koduck.dto.ai.BacktestInterpretRequest;
import com.koduck.dto.ai.BacktestInterpretResponse;
import com.koduck.dto.ai.ChatStreamRequest;
import com.koduck.dto.ai.RiskAssessmentRequest;
import com.koduck.dto.ai.RiskAssessmentResponse;
import com.koduck.dto.ai.StockAnalysisRequest;
import com.koduck.dto.ai.StockAnalysisResponse;
import com.koduck.dto.ai.StrategyRecommendRequest;
import com.koduck.dto.ai.StrategyRecommendResponse;
import com.koduck.entity.MemoryChatMessage;
import com.koduck.security.UserPrincipal;
import com.koduck.service.AiAnalysisService;
import com.koduck.service.MemoryService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * REST API controller exposing AI analysis endpoints.
 *
 * <p>Clients use this controller to request stock analysis, strategy
 * recommendations, backtest interpretation, and portfolio risk assessment.
 * All endpoints require authenticated credentials.</p>
 *
 * @author GitHub Copilot
 */
@RestController
@RequestMapping("/api/v1/ai")
@Tag(name = "AI分析", description = "智能股票分析、策略推荐、风险评估等AI分析接口")
@SecurityRequirement(name = "bearerAuth")
@Slf4j
@RequiredArgsConstructor
public class AiAnalysisController {

    /** Key for session ID in response maps. */
    private static final String KEY_SESSION_ID = "sessionId";

    /** Service for AI analysis operations. */
    private final AiAnalysisService aiAnalysisService;

    /** Service for memory operations. */
    private final MemoryService memoryService;

    /** Resolver for extracting authenticated user information. */
    private final AuthenticatedUserResolver authenticatedUserResolver;

    /**
     * Perform an AI-driven stock analysis.
     *
     * <p>The results are generated by the {@link AiAnalysisService} and include
     * technical, fundamental and sentiment assessments.</p>
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        request payload containing symbol, market and analysis
     *                       type
     * @return a successful {@link ApiResponse} wrapping the analysis result
     */
    @Operation(
        summary = "AI股票分析",
        description = "使用AI对指定股票进行技术面、基本面、情绪面综合分析"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "200",
                description = "分析成功",
                content = @Content(schema = @Schema(implementation = StockAnalysisResponse.class))
            ),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "请求参数错误"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "429", description = "AI分析请求过于频繁"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误或AI服务不可用")
    })
    @PostMapping("/analyze")
    public ApiResponse<StockAnalysisResponse> analyzeStock(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody StockAnalysisRequest request) {
        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/analyze: user={}, symbol={}, question={}",
            userId, request.getSymbol(), request.getQuestion());
        StockAnalysisResponse response = aiAnalysisService.analyzeStock(userId, request);
        return ApiResponse.success(response);
    }

    /**
     * Proxy chat stream request through backend for unified AI access.
     *
     * @param userPrincipal the authenticated user principal
     * @param request the chat stream request
     * @return SSE emitter for streaming response
     */
    @Operation(
        summary = "AI流式对话",
        description = "与AI进行流式对话，使用SSE协议返回"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "流式响应开始"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "请求参数错误"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @PostMapping(value = "/chat/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public SseEmitter chatStream(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody ChatStreamRequest request) {
        Long userId = requireUserId(userPrincipal);
        log.debug(
            "POST /api/v1/ai/chat/stream: user={}, provider={}, model={}",
            userId,
            request.getProvider(),
            request.getModel()
        );
        return aiAnalysisService.streamChat(userId, request);
    }

    /**
     * Generate strategy recommendations for the user.
     *
     * <p>The request includes risk preference and investment horizon. The
     * service will return a list of candidate strategies along with a
     * suggested asset allocation.</p>
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        strategy recommendation request data
     * @return an {@link ApiResponse} with strategy recommendations
     */
    @Operation(
        summary = "策略推荐",
        description = "根据用户风险偏好和投资期限生成策略推荐"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "200",
                description = "推荐成功",
                content = @Content(schema = @Schema(implementation = StrategyRecommendResponse.class))
            ),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "请求参数错误"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @PostMapping("/strategy-recommend")
    public ApiResponse<StrategyRecommendResponse> recommendStrategies(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody StrategyRecommendRequest request) {
        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/strategy-recommend: user={}, risk={}",
                 userId, request.getRiskPreference());
        StrategyRecommendResponse response = aiAnalysisService.recommendStrategies(userId, request);
        return ApiResponse.success(response);
    }

    /**
     * Interpret a previously run backtest result.
     *
     * <p>The user must own the backtest result identified in the request.</p>
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        contains the identifier of the backtest result
     * @return an {@link ApiResponse} containing interpretation details
     */
    @Operation(
        summary = "回测结果解读",
        description = "使用AI解读回测结果，分析策略表现"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "200",
                description = "解读成功",
                content = @Content(schema = @Schema(implementation = BacktestInterpretResponse.class))
            ),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "请求参数错误"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "无权访问该回测结果"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "回测结果不存在"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @PostMapping("/interpret-backtest")
    public ApiResponse<BacktestInterpretResponse> interpretBacktest(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody BacktestInterpretRequest request) {
        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/interpret-backtest: user={}, backtestId={}",
                 userId, request.getBacktestResultId());
        BacktestInterpretResponse response = aiAnalysisService.interpretBacktest(
            userId,
            request.getBacktestResultId()
        );
        return ApiResponse.success(response);
    }

    /**
     * Perform a risk assessment on the user's portfolio.
     *
     * @param userPrincipal the authenticated user principal, must not be null
     * @param request        contains the portfolio identifier to evaluate
     * @return an {@link ApiResponse} with risk metrics and suggestions
     */
    @Operation(
        summary = "投资组合风险评估",
        description = "使用AI评估投资组合风险，提供风险指标和改进建议"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "200",
                description = "评估成功",
                content = @Content(schema = @Schema(implementation = RiskAssessmentResponse.class))
            ),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "请求参数错误"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "无权访问该投资组合"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "投资组合不存在"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @PostMapping("/risk-assessment")
    public ApiResponse<RiskAssessmentResponse> assessRisk(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody RiskAssessmentRequest request) {
        Long userId = requireUserId(userPrincipal);
        log.debug("POST /api/v1/ai/risk-assessment: user={}, portfolioId={}",
                 userId, request.getPortfolioId());
        RiskAssessmentResponse response = aiAnalysisService.assessRisk(
            userId,
            request.getPortfolioId()
        );
        return ApiResponse.success(response);
    }

    /**
     * Delete session memory.
     *
     * @param userPrincipal the authenticated user principal
     * @param sessionId the session ID to delete
     * @return response indicating deletion success
     */
    @Operation(
        summary = "删除会话记忆",
        description = "删除指定AI对话会话的记忆"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "删除成功"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @DeleteMapping("/memory/session/{sessionId}")
    public ApiResponse<Map<String, Object>> deleteSession(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Parameter(description = "会话ID", example = "session_123")
            @PathVariable String sessionId
    ) {
        Long userId = requireUserId(userPrincipal);
        String normalizedSessionId = memoryService.resolveSessionId(sessionId);
        memoryService.deleteSession(userId, normalizedSessionId);
        return ApiResponse.success(Map.of(
                KEY_SESSION_ID, normalizedSessionId,
                "deleted", true
        ));
    }

    /**
     * Clear user memory.
     *
     * @param userPrincipal the authenticated user principal
     * @return response indicating clear success
     */
    @Operation(
        summary = "清除用户记忆",
        description = "清除当前用户的所有AI对话记忆"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "清除成功"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @DeleteMapping("/memory/profile")
    public ApiResponse<Map<String, Object>> clearProfileMemory(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal
    ) {
        Long userId = requireUserId(userPrincipal);
        memoryService.clearProfile(userId);
        return ApiResponse.success(Map.of("cleared", true));
    }

    /**
     * Get user sessions.
     *
     * @param userPrincipal the authenticated user principal
     * @return response containing list of user sessions
     */
    @Operation(
        summary = "获取用户会话列表",
        description = "获取当前用户的所有AI对话会话"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "获取成功"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @GetMapping("/memory/sessions")
    public ApiResponse<Map<String, Object>> listUserSessions(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal
    ) {
        Long userId = requireUserId(userPrincipal);
        var sessions = memoryService.getUserSessions(userId);
        var sessionList = sessions.stream().map(s -> Map.<String, Object>of(
            KEY_SESSION_ID, s.getSessionId(),
            "title", s.getTitle() != null ? s.getTitle() : s.getSessionId(),
            "status", s.getStatus(),
            "lastMessageAt", s.getLastMessageAt() != null ? s.getLastMessageAt().toString() : "",
            "createdAt", s.getCreatedAt() != null ? s.getCreatedAt().toString() : ""
        )).toList();
        return ApiResponse.success(Map.of("sessions", sessionList));
    }

    /**
     * Get session memory summary.
     *
     * @param userPrincipal the authenticated user principal
     * @param sessionId the session ID to query
     * @return response containing session memory summary
     */
    @Operation(
        summary = "获取会话记忆详情",
        description = "获取指定AI对话会话的详细记忆内容"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "获取成功"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录或Token无效"),
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "服务器内部错误")
    })
    @GetMapping("/memory/session/{sessionId}")
    public ApiResponse<Map<String, Object>> getSessionMemorySummary(
            @Parameter(description = "当前用户认证信息", hidden = true)
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Parameter(description = "会话ID", example = "session_123")
            @PathVariable String sessionId
    ) {
        Long userId = requireUserId(userPrincipal);
        String normalizedSessionId = memoryService.resolveSessionId(sessionId);
        List<MemoryChatMessage> messages = memoryService.getRecentMessages(
                userId,
                normalizedSessionId,
                memoryService.getL1MaxTurns()
        );
        List<Map<String, Object>> summary = messages.stream().map(m -> Map.<String, Object>of(
                "role", m.getRole() != null ? m.getRole() : "unknown",
                "content", m.getContent() != null ? m.getContent() : "",
                "createdAt", m.getCreatedAt() != null ? m.getCreatedAt().toString() : ""
        )).toList();
        return ApiResponse.success(Map.of(
                KEY_SESSION_ID, normalizedSessionId,
                "messageCount", summary.size(),
                "messages", summary
        ));
    }

    private Long requireUserId(UserPrincipal userPrincipal) {
        return authenticatedUserResolver.requireUserId(userPrincipal);
    }
}
