#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, "..");
const configDir = path.join(packageRoot, "config", "di");
const outputDir = path.join(packageRoot, "src", "common", "di", "generated");
const outputFile = path.join(outputDir, "core-services.ts");
const tokensFile = path.join(packageRoot, "src", "common", "di", "tokens.ts");

const IMPORT_BASE = {
  type: [{ name: "CoreServiceRegistration", from: "../core-service-registration" }],
  value: [{ name: "TOKENS", from: "../tokens" }],
};

function readConfigFiles() {
  const entries = readdirSync(configDir, { withFileTypes: true });
  const results = [];

  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const ext = path.extname(entry.name).toLowerCase();
    if (![".yaml", ".yml", ".json"].includes(ext)) continue;
    const fullPath = path.join(configDir, entry.name);
    const raw = readFileSync(fullPath, "utf8");
    const parsed = ext === ".json" ? JSON.parse(raw) : parseYaml(raw);
    if (!parsed || typeof parsed !== "object") {
      throw new Error(`Unsupported config shape in ${entry.name}`);
    }
    results.push({ file: entry.name, config: parsed });
  }

  if (results.length === 0) {
    throw new Error(`No DI config files found in ${configDir}`);
  }

  return results;
}

function normaliseImport(entry, sourceFile) {
  if (!entry?.name || !entry?.from) {
    throw new Error(`Invalid import entry in ${sourceFile}`);
  }
  return {
    name: entry.name,
    from: entry.from,
    alias: entry.alias,
    typeOnly: Boolean(entry.typeOnly),
  };
}

function normaliseService(service, sourceFile) {
  const required = ["key", "token", "lifecycle", "ownsInstance", "factory"];
  for (const field of required) {
    if (!(field in service)) {
      throw new Error(`${field} is required for service in ${sourceFile}`);
    }
  }
  return {
    key: service.key,
    token: service.token,
    lifecycle: service.lifecycle,
    ownsInstance: Boolean(service.ownsInstance),
    dispose: service.dispose ?? null,
    factory: String(service.factory),
  };
}

function collectConfig() {
  const files = readConfigFiles();
  const imports = new Map();
  const services = [];

  for (const { file, config } of files) {
    const localImports = Array.isArray(config.imports) ? config.imports : [];
    for (const entry of localImports) {
      const normalised = normaliseImport(entry, file);
      const bucketKey = `${normalised.from}|${normalised.typeOnly ? "type" : "value"}`;
      let bucket = imports.get(bucketKey);
      if (!bucket) {
        bucket = {
          from: normalised.from,
          typeOnly: normalised.typeOnly,
          names: new Map(),
        };
        imports.set(bucketKey, bucket);
      }
      const existingAlias = bucket.names.get(normalised.name);
      if (existingAlias && existingAlias !== normalised.alias) {
        throw new Error(
          `Conflicting alias for import ${normalised.name} from ${normalised.from} in ${file}`
        );
      }
      bucket.names.set(normalised.name, normalised.alias ?? null);
    }

    const serviceNodes = Array.isArray(config.services) ? config.services : [];
    for (const service of serviceNodes) {
      services.push({ ...normaliseService(service, file), source: file });
    }
  }

  services.sort((a, b) => a.key.localeCompare(b.key));

  return { imports, services };
}

function ensureOutputDir() {
  mkdirSync(outputDir, { recursive: true });
}

function formatExpression(expr) {
  const trimmed = expr.trim();
  if (!trimmed.includes("\n")) {
    return trimmed;
  }
  const [first, ...rest] = trimmed.split("\n");
  const continuationIndent = "        ";
  const meaningful = rest.filter((line) => line.trim().length > 0);
  const minIndent = meaningful.length
    ? Math.min(...meaningful.map((line) => line.match(/^\s*/)[0].length))
    : 0;
  const indented = rest.map((line) => {
    const sliced = line.slice(Math.min(minIndent, line.length));
    return `${continuationIndent}${sliced}`.replace(/[ \t]+$/, "");
  });
  return `${first}\n${indented.join("\n")}`;
}

function buildRegistrySource(imports, services) {
  const header = `/**\n * This file is auto-generated by scripts/build-di.mjs.\n * Do not edit this file directly.\n */\n`;

  const mergedImports = new Map();
  for (const kind of Object.keys(IMPORT_BASE)) {
    for (const entry of IMPORT_BASE[kind]) {
      const bucketKey = `${entry.from}|${kind}`;
      let bucket = mergedImports.get(bucketKey);
      if (!bucket) {
        bucket = { from: entry.from, typeOnly: kind === "type", names: new Map() };
        mergedImports.set(bucketKey, bucket);
      }
      bucket.names.set(entry.name, entry.alias ?? null);
    }
  }

  for (const bucket of imports.values()) {
    const key = `${bucket.from}|${bucket.typeOnly ? "type" : "value"}`;
    let target = mergedImports.get(key);
    if (!target) {
      target = { from: bucket.from, typeOnly: bucket.typeOnly, names: new Map() };
      mergedImports.set(key, target);
    }
    for (const [name, alias] of bucket.names.entries()) {
      const existing = target.names.get(name);
      if (existing && existing !== alias) {
        throw new Error(`Conflicting alias detected for ${name} from ${bucket.from}`);
      }
      target.names.set(name, alias);
    }
  }

  const importBlocks = Array.from(mergedImports.values())
    .sort((a, b) => a.from.localeCompare(b.from))
    .map((bucket) => {
      const specifiers = Array.from(bucket.names.entries())
        .sort((a, b) => a[0].localeCompare(b[0]))
        .map(([name, alias]) => (alias ? `${name} as ${alias}` : name))
        .join(", ");
      const importKeyword = bucket.typeOnly ? "import type" : "import";
      return `${importKeyword} { ${specifiers} } from "${bucket.from}";`;
    });

  const registryEntries = services.map((service) => {
    const lines = [
      `  ${service.key}: {`,
      `    token: TOKENS.${service.token},`,
      `    factory: ${formatExpression(service.factory)},`,
      `    lifecycle: "${service.lifecycle}",`,
      `    ownsInstance: ${service.ownsInstance},`,
    ];
    if (service.dispose) {
      lines.push(`    dispose: ${formatExpression(service.dispose)},`);
    }
    lines.push("  },");
    return lines.join("\n");
  });

  const body = [
    ...importBlocks,
    "",
    "export const CORE_SERVICE_REGISTRY = {",
    ...registryEntries,
    "} satisfies Record<string, CoreServiceRegistration<unknown>>;",
    "",
  ].join("\n");

  return `${header}${body}`;
}

function loadTokenKeys() {
  const tokensSource = readFileSync(tokensFile, "utf8");
  const bodyMatch = tokensSource.match(/TOKENS\s*=\s*{([\s\S]*?)}\s*as const\s*;/);
  if (!bodyMatch) {
    throw new Error(
      `Unable to locate TOKENS definition in ${path.relative(packageRoot, tokensFile)}`
    );
  }

  const keyPattern = /([A-Za-z0-9_]+)\s*:/g;
  const keys = new Set();
  let match;
  while ((match = keyPattern.exec(bodyMatch[1])) !== null) {
    const key = match[1];
    if (key) {
      keys.add(key);
    }
  }

  if (keys.size === 0) {
    throw new Error(`No DI tokens found in ${path.relative(packageRoot, tokensFile)}`);
  }

  return keys;
}

function validateTokenUsage(services, definedTokens) {
  const usage = new Map();

  for (const service of services) {
    if (!definedTokens.has(service.token)) {
      throw new Error(
        `Service "${service.key}" (from ${service.source}) references undefined token "${service.token}". ` +
          `Add it to ${path.relative(packageRoot, tokensFile)} before regenerating.`
      );
    }

    const existing = usage.get(service.token);
    if (existing) {
      throw new Error(
        `Token "${service.token}" is used by multiple services: "${existing.key}" (${existing.source}) and "${service.key}" (${service.source}).`
      );
    }

    usage.set(service.token, { key: service.key, source: service.source });
  }
}

function ensureGeneratedFileUpToDate(expectedSource) {
  if (!existsSync(outputFile)) {
    throw new Error(
      `Generated DI registry missing at ${path.relative(packageRoot, outputFile)}. Run "pnpm -C packages/duck-flow run build:di".`
    );
  }

  const current = readFileSync(outputFile, "utf8");
  if (current !== expectedSource) {
    throw new Error(
      `Generated DI registry is out of date. Run "pnpm -C packages/duck-flow run build:di" and commit the changes.`
    );
  }
}

function main() {
  const checkOnly = process.argv.slice(2).includes("--check");
  const { imports, services } = collectConfig();
  const definedTokens = loadTokenKeys();
  validateTokenUsage(services, definedTokens);
  const source = buildRegistrySource(imports, services);
  if (checkOnly) {
    ensureGeneratedFileUpToDate(source);
    return;
  }

  ensureOutputDir();
  writeFileSync(outputFile, `${source}`);
}

main();
