import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { ENV_VAR_DEFINITIONS } from "../src/common/config/loader/env-definitions";

type DefaultValue = string | number | boolean;

type TableRow = {
  variable: string;
  targetPath: string;
  type: string;
  defaultValue: DefaultValue;
  category: string;
  requirementRef?: string;
  description: string;
};

async function main(): Promise<void> {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const projectRoot = path.resolve(scriptDir, "..", "");

  const templatePath = path.resolve(projectRoot, "config", ".env.template");
  const docPath = path.resolve(projectRoot, "docs", "configuration-env-reference.md");

  const tableData = buildTableData();
  const templateContent = buildTemplateContent(tableData);
  const docContent = buildDocContent(tableData);

  await writeFile(templatePath, templateContent, "utf8");
  await writeFile(docPath, docContent, "utf8");

  console.log(`Generated ${path.relative(projectRoot, templatePath)}`);
  console.log(`Generated ${path.relative(projectRoot, docPath)}`);
}

function buildTableData(): TableRow[] {
  return ENV_VAR_DEFINITIONS.map((definition) => ({
    variable: definition.name,
    targetPath: definition.targetPath,
    type: describeType(definition),
    defaultValue: definition.defaultValue,
    category: definition.category,
    requirementRef: definition.requirementRef,
    description: definition.description,
  }));
}

function buildTemplateContent(data: TableRow[]): string {
  const headerLines = [
    "# KoduckFlow configuration environment template",
    "# Auto-generated by pnpm run config:sync-env -- do not edit manually",
    `# Generated at ${new Date().toISOString()}`,
    "",
  ];

  const bodyLines = data.flatMap((row) => {
    const annotations = [
      `# ${row.description}`,
      `# Target: ${row.targetPath}`,
      `# Category: ${row.category}`,
    ];

    if (row.requirementRef) {
      annotations.push(`# Requirement: ${row.requirementRef}`);
    }

    annotations.push(`# Default: ${formatDefaultValue(row.defaultValue)}`);

    return [...annotations, `${row.variable}=${formatEnvValue(row.defaultValue)}`, ""];
  });

  return [...headerLines, ...bodyLines].join("\n");
}

function buildDocContent(data: TableRow[]): string {
  const disclaimer =
    "<!-- AUTO-GENERATED: config-env -- do not edit manually. Update via pnpm run config:sync-env -->";

  const header = [
    "# KoduckFlow Environment Variable Reference",
    "",
    disclaimer,
    "",
    "This document lists configuration overrides available through environment variables.",
    "",
  ];

  const tableHeader =
    "| Variable | Target Path | Type | Default | Category | Requirement | Description |";
  const tableSeparator = "| --- | --- | --- | --- | --- | --- | --- |";

  const tableRows = data.map((row) => {
    const requirement = row.requirementRef ?? "—";
    return `| ${row.variable} | ${row.targetPath} | ${row.type} | ${formatDefaultValue(
      row.defaultValue
    )} | ${row.category} | ${requirement} | ${row.description} |`;
  });

  return [...header, tableHeader, tableSeparator, ...tableRows, ""].join("\n");
}

function describeType(definition: (typeof ENV_VAR_DEFINITIONS)[number]): string {
  const spec = definition.value;
  if (spec.type === "enum") {
    return `enum(${spec.values.join(", ")})`;
  }

  return spec.type;
}

function formatDefaultValue(value: DefaultValue): string {
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "number") {
    return value.toString();
  }
  return `\`${value}\``;
}

function formatEnvValue(value: DefaultValue): string {
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  return String(value);
}

await main();
